### ISSUE TITLE
console being spammed 

### ISSUE THREAD

**Issue by SDUBZ** [Kukupie123/KukusVillagerModV2_Valheim#1]
hello i just installed your mod and loaded it up since making the bed and letting some spawn my console is being spammed with
Warning:KukusVillagerMod.KLog] Destroying Villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Villager Found UID $4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Failed to find empyty bed!! for villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Destroying Villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Villager Found UID $4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Failed to find empyty bed!! for villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Destroying Villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Villager Found UID $4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Failed to find empyty bed!! for villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Destroying Villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Villager Found UID $4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Info   : Unity Log] 01/01/2023 18:52:16: Destroyed invalid predab ZDO:-285861384:3144

[Info   : Unity Log] 01/01/2023 18:52:16: Destroyed invalid predab ZDO:-285861384:3142

[Info   : Unity Log] 01/01/2023 18:52:16: Destroyed invalid predab ZDO:-285861384:3143

[Warning:KukusVillagerMod.KLog] Failed to find empyty bed!! for villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Destroying Villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Villager Found UID $4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Info   : Unity Log] 01/01/2023 18:52:16: Destroyed invalid predab ZDO:-285861384:3146

[Warning:KukusVillagerMod.KLog] Failed to find empyty bed!! for villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Destroying Villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Villager Found UID $4912f46c-e4f3-4484-863c-46cd1dc50ae9
[Warning:KukusVillagerMod.KLog] Failed to find empyty bed!! for villager 4912f46c-e4f3-4484-863c-46cd1dc50ae9
and keeps going not stoping 
any advice would be nice 
using version 1.0.0 of the mod from thunderstore mod manager

**Comment by kuchuk-borom-debbarma** [comment]
Hi, Just to be sure this is where you downloaded the mod from right? https://valheim.thunderstore.io/package/KukuPie/Kukus_Village/

And this bug happened when you would go far away from a villager and it gets unloaded and you come back just close enough for the game to load the villager but not all of it's data so the villager fails to find a bed and is destroyed as a villager can't exist without a bed is how it was coded but then the game keeps spawning them and the loop continues. 

This bug should have been solved but maybe it's not fully fixed. Can you send me your world so that I can test my mod in there and fix the bug since I will not be able to replicate the bug in my world

**Comment by SDUBZ** [comment]
> Hi, Just to be sure this is where you downloaded the mod from right? https://valheim.thunderstore.io/package/KukuPie/Kukus_Village/
> 
> And this bug happened when you would go far away from a villager and it gets unloaded and you come back just close enough for the game to load the villager but not all of it's data so the villager fails to find a bed and is destroyed as a villager can't exist without a bed is how it was coded but then the game keeps spawning them and the loop continues.
> 
> This bug should have been solved but maybe it's not fully fixed. Can you send me your world so that I can test my mod in there and fix the bug since I will not be able to replicate the bug in my world

yes that's where i downloaded it from, and the spam stops if you destroy bed and villagers are gone from world too
when the spam is going on it drops my fps from 50+ to 6 fps
i could send you the file that has all the mods i have maybe its a conflict happening that i can not see

**Comment by SDUBZ** [comment]
> Hi, Just to be sure this is where you downloaded the mod from right? https://valheim.thunderstore.io/package/KukuPie/Kukus_Village/
> 
> And this bug happened when you would go far away from a villager and it gets unloaded and you come back just close enough for the game to load the villager but not all of it's data so the villager fails to find a bed and is destroyed as a villager can't exist without a bed is how it was coded but then the game keeps spawning them and the loop continues.
> 
> This bug should have been solved but maybe it's not fully fixed. Can you send me your world so that I can test my mod in there and fix the bug since I will not be able to replicate the bug in my world

yes that's where i downloaded it from, and the spam stops if you destroy bed and villagers are gone from world too
when the spam is going on it drops my fps from 50+ to 6 fps

**Comment by SDUBZ** [comment]
[worlds_local.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10328816/worlds_local.zip)
[mods.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10328817/mods.zip)
here is the world and here is the mods import file through thunder mod manager

**Comment by kuchuk-borom-debbarma** [comment]
> [worlds_local.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10328816/worlds_local.zip) [mods.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10328817/mods.zip) here is the world and here is the mods import file through thunder mod manager

Hi, I made some changes to how the villagers and beds are linked. Will you be interested in testing it out? It will not feature the commander club and all those things but I would love if you could test and let me know how reliable this new method is. I will send you the plugin if you are okay to test it out

**Comment by SDUBZ** [comment]
yes i would love too

**Comment by kuchuk-borom-debbarma** [comment]
[KukusVillagerMod.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10330246/KukusVillagerMod.zip)
Here you go. test if this is stable and fixed your issue. If yes then I will update the mod with this code :)

**Comment by SDUBZ** [comment]
> [KukusVillagerMod.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10330246/KukusVillagerMod.zip) Here you go. test if this is stable and fixed your issue. If yes then I will update the mod with this code :)

okay will test in a few seconds

**Comment by SDUBZ** [comment]
okay it still spams but only does so once another person joins you with the same mod

**Comment by SDUBZ** [comment]
I do have a theory what might be happening its acting like 2 instances and the mod is fighting with the other person and my mod to get villagers or multiplying for each person bed and villages ect, if you get what i mean kinda like if you had a server mod on the clients and the server they all gonna fight and yell about this that and the other

**Comment by SDUBZ** [comment]
my theory is correct if 2 people have the mod loaded and they join one another disaster
so i would recommend this build and maybe a big caption in the description of mod [only host need this mod]or label it as server sided

**Comment by kuchuk-borom-debbarma** [comment]
Thank you for testing it. Really gave an insight. But do the villagers spawn for a player who doesn't have the mod? I suppose it doesn't. I may add a client only dll too that should be installed by the client so that the villagers and bed spawn but will have no logic or control over the spawning. Until then I will update the description mentioning this :)

**Comment by SDUBZ** [comment]
if you do have only one side loaded with the mod the other person cant see the 

> Thank you for testing it. Really gave an insight. But do the villagers spawn for a player who doesn't have the mod? I suppose it doesn't. I may add a client only dll too that should be installed by the client so that the villagers and bed spawn but will have no logic or control over the spawning. Until then I will update the description mentioning this :)

to be noted: if you do have only one side loaded with the mod the other person cant see the villagers from the mod

**Comment by kuchuk-borom-debbarma** [comment]
Give me few mins. I will try to disable logic if the player is not a host. and send you the file. Put it on the client and see if it works

**Comment by kuchuk-borom-debbarma** [comment]
[KukusVillagerMod.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10331094/KukusVillagerMod.zip)
Give this a go and let me know if this is any better. I have not worked with multiplayer part of unity so I am not sure what works best and what doesn't

**Comment by SDUBZ** [comment]
> [KukusVillagerMod.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10331094/KukusVillagerMod.zip) Give this a go and let me know if this is any better. I have not worked with multiplayer part of unity so I am not sure what works best and what doesn't

is this for the host or the client ?

**Comment by kuchuk-borom-debbarma** [comment]
its for both. It should be able to figure out which one is the server.

**Comment by SDUBZ** [comment]
> its for both. It should be able to figure out which one is the server.

seems to be good now and my friend can see the villagers only output was

[Warning:KukusVillagerMod.KLog] Seaching bed for villager ba82fb2f-4eba-4816-8e95-e4d686b9ec7b
[Warning:KukusVillagerMod.KLog] Seaching bed FAILED for villager ba82fb2f-4eba-4816-8e95-e4d686b9ec7b
[Warning:KukusVillagerMod.KLog] Searchig villager STARTED for bed ec8c1129-977c-40cc-83cc-ab17284d36e1
[Warning:KukusVillagerMod.KLog] Searchig villager FAILED for bed ec8c1129-977c-40cc-83cc-ab17284d36e1
[Warning:KukusVillagerMod.KLog] creating villager for bed ec8c1129-977c-40cc-83cc-ab17284d36e1
[Warning:KukusVillagerMod.KLog] Created UID for Villager 042d07f8-5bb9-47ad-925d-4d93f4b14542
[Warning:KukusVillagerMod.KLog] Found UID for Villager 042d07f8-5bb9-47ad-925d-4d93f4b14542
[Warning:KukusVillagerMod.KLog] Villager 042d07f8-5bb9-47ad-925d-4d93f4b14542  saved beds UID ec8c1129-977c-40cc-83cc-ab17284d36e1

[Warning:KukusVillagerMod.KLog] Found UID for Villager 46560469-985f-4ace-98a5-ea636deccbea
[Warning:KukusVillagerMod.KLog] Found UID for Villager ba82fb2f-4eba-4816-8e95-e4d686b9ec7b
[Warning:KukusVillagerMod.KLog] Found UID for bed ec8c1129-977c-40cc-83cc-ab17284d36e1
[Warning:KukusVillagerMod.KLog] Searchig villager STARTED for bed ec8c1129-977c-40cc-83cc-ab17284d36e1
[Warning:KukusVillagerMod.KLog] Villager 46560469-985f-4ace-98a5-ea636deccbea  saved beds UID ec8c1129-977c-40cc-83cc-ab17284d36e1
[Warning:KukusVillagerMod.KLog] Searchig villager SUCCESS for bed ec8c1129-977c-40cc-83cc-ab17284d36e1, FOUND 46560469-985f-4ace-98a5-ea636deccbea
[Warning:KukusVillagerMod.KLog] Found UID for bed 3f1032fc-29f8-4904-9d04-904644f87cd5
[Warning:KukusVillagerMod.KLog] Searchig villager STARTED for bed 3f1032fc-29f8-4904-9d04-904644f87cd5
[Warning:KukusVillagerMod.KLog] Searchig villager FAILED for bed 3f1032fc-29f8-4904-9d04-904644f87cd5
[Warning:KukusVillagerMod.KLog] creating villager for bed 3f1032fc-29f8-4904-9d04-904644f87cd5
[Warning:KukusVillagerMod.KLog] Created UID for Villager 47013abf-e93c-4f5c-8871-278e170a6889
[Warning:KukusVillagerMod.KLog] Found UID for Villager 47013abf-e93c-4f5c-8871-278e170a6889
[Warning:KukusVillagerMod.KLog] Villager 47013abf-e93c-4f5c-8871-278e170a6889  saved beds UID 3f1032fc-29f8-4904-9d04-904644f87cd5
[Warning:KukusVillagerMod.KLog] Seaching bed for villager 46560469-985f-4ace-98a5-ea636deccbea
[Warning:KukusVillagerMod.KLog] Villager 46560469-985f-4ace-98a5-ea636deccbea  saved beds UID ec8c1129-977c-40cc-83cc-ab17284d36e1
[Warning:KukusVillagerMod.KLog] Found bed for villager 46560469-985f-4ace-98a5-ea636deccbea , Bed : ec8c1129-977c-40cc-83cc-ab17284d36e1

**Comment by kuchuk-borom-debbarma** [comment]
Nice those message are just to let others know if bed has found a villager and villager has found a bed. I just labelled them warning as it's easy to notice those lol. Anyways this isn't a permanent fix sadly. You will have to wait for a while before I can make things stable specially for multiplayer :(. Your clients will not be able to have full control over the villagers and villagers finding bed/ bed finding villagers will only work when the server owner is nearby I think. I hope you can understand. But this should let you play with your friend for a while. I will send you one last fully built mod before I release it to nexus mod. I hope you can test it out too :)

**Comment by SDUBZ** [comment]
> Nice those message are just to let others know if bed has found a villager and villager has found a bed. I just labelled them warning as it's easy to notice those lol. Anyways this isn't a permanent fix sadly. You will have to wait for a while before I can make things stable specially for multiplayer :(. Your clients will not be able to have full control over the villagers and villagers finding bed/ bed finding villagers will only work when the server owner is nearby I think. I hope you can understand. But this should let you play with your friend for a while. I will send you one last fully built mod before I release it to nexus mod. I hope you can test it out too :)

thank you and ofc would be fun too

**Comment by SDUBZ** [comment]
the spam is back again

**Comment by SDUBZ** [comment]
how long do you have it check for beds ? or make it spawn more villagers from same bed

**Comment by kuchuk-borom-debbarma** [comment]
The bed checks happen ONLY ONCE per villager. When it's loaded in memory but the game sometime has not initialized the beds and this ends up spawning and killing villager over and over. I thought this must have been solved. Can you send me your latest world so that i can see why this is happening

**Comment by SDUBZ** [comment]
> The bed checks happen ONLY ONCE per villager. When it's loaded in memory but the game sometime has not initialized the beds and this ends up spawning and killing villager over and over. I thought this must have been solved. Can you send me your latest world so that i can see why this is 
yeah sure give me abit

**Comment by SDUBZ** [comment]
[worlds_local.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10331667/worlds_local.zip)

**Comment by kuchuk-borom-debbarma** [comment]
can you send me your player too since if i use mine i spawn at starting altar

**Comment by SDUBZ** [comment]
[sdubz.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10331710/sdubz.zip)

**Comment by SDUBZ** [comment]
new bug the bronze villager doesn't die if you kill their beds

**Comment by kuchuk-borom-debbarma** [comment]
Just tested it out and it's working fine here. I will send you the dll that i am using right now. I may have done something wrong in the dll i sent earlier which i corrected later on.
![Screenshot (164)](https://user-images.githubusercontent.com/45627511/210235398-00c7aca7-b323-4251-805c-f31fedd251ca.png)
![Screenshot (159)](https://user-images.githubusercontent.com/45627511/210235419-e9cca471-d9eb-4d82-ad75-a5997f331358.png)

**Comment by SDUBZ** [comment]
> Just tested it out and it's working fine here. I will send you the dll that i am using right now. I may have done something wrong in the dll i sent earlier which i corrected later on. ![Screenshot (164)](https://user-images.githubusercontent.com/45627511/210235398-00c7aca7-b323-4251-805c-f31fedd251ca.png) ![Screenshot (159)](https://user-images.githubusercontent.com/45627511/210235419-e9cca471-d9eb-4d82-ad75-a5997f331358.png)

okay looking forward to it

**Comment by kuchuk-borom-debbarma** [comment]
Check out the latest version I uploaded

**Comment by SDUBZ** [comment]
what was the other mod you wanted tested

**Comment by SDUBZ** [comment]
> Check out the latest version I uploaded

the spam is back afetr traveling abit through portals im not sure why

**Comment by kuchuk-borom-debbarma** [comment]
> > Check out the latest version I uploaded
> 
> the spam is back afetr traveling abit through portals im not sure why

ah that sucks. Time for you to send your world and character save again :)

**Comment by kuchuk-borom-debbarma** [comment]
and tell me what will i have to do to replicate the bug

**Comment by SDUBZ** [comment]
it spammed like crazy then stopped not sure if its when i travel back to main base or when its fully loaded kinda thing

**Comment by kuchuk-borom-debbarma** [comment]
> it spammed like crazy then stopped not sure if its when i travel back to main base or when its fully loaded kinda thing

how long does the spam last for? and how many villagers do you have. It does spam quite a lot of thing when an area with lots of villagers is loaded but then calms down. If that is what you are experiencing then it is intended. 

If the spam is infinite then its a bug

**Comment by SDUBZ** [comment]
like 5 to 15 mins then randomly dies off

**Comment by kuchuk-borom-debbarma** [comment]
> like 5 to 15 mins then randomly dies off

Damn that is a lot. it should not be that long. Care to send me your world and character?

**Comment by SDUBZ** [comment]
yes i will in a second

**Comment by SDUBZ** [comment]
[sdubz.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10336711/sdubz.zip)
[worlds_local.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10336713/worlds_local.zip)

**Comment by kuchuk-borom-debbarma** [comment]
Loads fine, How do i replicate the infinite spamming. WHere is the console?

**Comment by kuchuk-borom-debbarma** [comment]
Hi, I went through every portal and it seemed to work fine. I guess another mod is conflicting? I am playing SP offline tho

**Comment by SDUBZ** [comment]
valheim seems to have a syncing problem and chunk kinda issues

**Comment by SDUBZ** [comment]
like the handshake between players is kinda bad at times and desyncs all over the place

**Comment by kuchuk-borom-debbarma** [comment]
> like the handshake between players is kinda bad at times and desyncs all over the place

 Maybe. I will try to overhaul the project to fit multiplayer well once i understand it better. :) Until then I guess single player is what it's going to be preferred

**Comment by SDUBZ** [comment]
i wonder how broken it would get with the beta version of valheim,in my modded experience some ebta versions work better then stable

**Comment by SDUBZ** [comment]
[Player-prev.log](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10341219/Player-prev.log)
thought i would send ya a log so you could spot something that may happen to me but not you

**Comment by kuchuk-borom-debbarma** [comment]
> [Player-prev.log](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10341219/Player-prev.log) thought i would send ya a log so you could spot something that may happen to me but not you

I figured out how valheim handles single creature spawn and implemented it in this mod. Would you like to test it out?

**Comment by kuchuk-borom-debbarma** [comment]
It should work okay in multiplayer too since its valheim's way of doing it

**Comment by SDUBZ** [comment]
can i ask something it might be your logic here but the villagers are looking for beds after they spawn right ? how come the bed becomes a container not a bed

**Comment by kuchuk-borom-debbarma** [comment]
> can i ask something it might be your logic here but the villagers are looking for beds after they spawn right ? how come the bed becomes a container not a bed

Oh that is because I originally wanted the beds to act as a container too so I added container features to the bed. I removed it in my current version. It should work with multiplayer mode too. Do test it I will send you when its somewhat done

**Comment by SDUBZ** [comment]
> > can i ask something it might be your logic here but the villagers are looking for beds after they spawn right ? how come the bed becomes a container not a bed
> 
> Oh that is because I originally wanted the beds to act as a container too so I added container features to the bed. I removed it in my current version. It should work with multiplayer mode too. Do test it I will send you when its somewhat done

i noticed from last version that iron class would stay in world for ages i killed beds

**Comment by kuchuk-borom-debbarma** [comment]
> > > can i ask something it might be your logic here but the villagers are looking for beds after they spawn right ? how come the bed becomes a container not a bed
> > 
> > 
> > Oh that is because I originally wanted the beds to act as a container too so I added container features to the bed. I removed it in my current version. It should work with multiplayer mode too. Do test it I will send you when its somewhat done
> 
> i noticed from last version that iron class would stay in world for ages i killed beds

Are you willing to test out the new version? And let me know how it works in multiplayer with your friends

**Comment by SDUBZ** [comment]
yeah i can test it

**Comment by kuchuk-borom-debbarma** [comment]
Test it in a new world and delete old config file. Test all commands including follow player, move to, etc etc along with your friend :) . If it works well in new world then we can try it in your original world too, I will make sure to credit you in the next update for testing the mods out
[Package.zip](https://github.com/Kukupie123/KukusVillagerModV2_Valheim/files/10351895/Package.zip)

**Comment by kuchuk-borom-debbarma** [comment]
> yeah i can test it

dont forget to read the read me things have changed significantly
