### ISSUE TITLE
Keypad commands not responsive

### ISSUE THREAD

**Issue by Enscryptor** [Kukupie123/KukusVillagerModV2_Valheim#2]
First, I absolutely love this mod for reasons made clear below ...

Deleted mod and config before update from 1.00 to 1.10

Changed keystrokes to F, G, H for Follow, Go, Home purely for convenience. Did not respond so I deleted the config and relaunched but all Keypad (Numlock on) also got no response.

Can always go back to 1.00 as I was pretty happy with it.

Feature, not bug:

Wasn't fond of having a Skeleton running around my base so I changed all the Melee models to DvergerMage :D

Mage casts fireball at innocent Greyling that wandered by.

From inside the house.

Reconstruction impeded because I couldn't stop laughing ...

Excellent mod, keep up the effort. I love having guards for my buildings instead of digging ditches and earthworks.

**Comment by kuchuk-borom-debbarma** [comment]
haha trust me those dverger with staffs are so chaotic. Also yes the keys are not responsive at the moment, eg if you press too multiple keys together it doesnt work. I also didn't really test if changing keys work, i will give a look at inputs in the near future once I add villagers who can farm stuffs :). New version has many changes and will need you to delete your old beds and villagers or worst case scenario, need to start a new world. really not hoping for it tho

**Comment by Enscryptor** [comment]
Should have been obvious that the AI package would come with the named entity, It was totally hilarious. Surprises are hard to come by.

So far it has been sufficient to just delete the mod before new installation. I'd prefer not to lose a world but have no resistance to starting a new one just for pretest before update.

What's your day job, if it's permitted to ask? I'm always looking to collect bright programmers ... keep them in contact for future projects.

**Comment by kuchuk-borom-debbarma** [comment]
hey I just tested the inputs and they do work :D
https://docs.unity3d.com/ScriptReference/KeyCode.html You can get the key codes from here. Its simple tho
![Screenshot (173)](https://user-images.githubusercontent.com/45627511/210648706-48cc61bb-106b-45bb-8710-50c3ac954ad5.png)

**Comment by Enscryptor** [comment]
I will retest but once I saw the same symptom from a fresh file with the KeyPad defaults I stopped worrying about it.

**Comment by Enscryptor** [comment]
Duh ... I forgot to hold the club. Case closed.

**Comment by kuchuk-borom-debbarma** [comment]
don't worry happens to the best of us lol. I been there. Spent 30 mins banging head just to realize I didnt hold the commander

**Comment by Enscryptor** [comment]
The Mage blowing holes in my base was an effective distraction. I think I'll reserve that for a trap ...

Will be watching for your next update.
