### ISSUE TITLE
Villagers multiplying

### ISSUE THREAD

**Issue by KneveTheKnight** [Kukupie123/KukusVillagerModV2_Valheim#3]
Villagers seem to multiply every 24hrs(roughly) by the number of beds there. Do you know if this is supposed to be a feature? Every time I log into the server for the day a new pair has spawned, so I have about 14 villagers with 2 beds. I have not changed any settings in the .dll or .cfg files

**Comment by kuchuk-borom-debbarma** [comment]
Are you in an multiplayer scenario? if yes then that is the issue, this mod is not currently working in multiplayer

**Comment by KneveTheKnight** [comment]
Yes on a dedicated server so it is multiplayer. Is there anything on my end I can do to help it work or is it something I have to wait for the mod to be updated to fix?

**Comment by kuchuk-borom-debbarma** [comment]
Villagers will not be spawned anymore from the next update. That should at least fix the infinite spawning villagers and although no where close to being supported should work in multiplayer without any serious bug
