### ISSUE TITLE
Cannot interact with Defense Posts.

### ISSUE THREAD

**Issue by ZestyJack** [Kukupie123/KukusVillagerModV2_Valheim#4]
As the title says you simply cannot interact with Defence Posts on the latest release (3.1.2 as of writing this issue). I have tested in both single player and a server to see if that makes a difference!
I also downgraded to 3.1.0 to see if it changes, but they still did not work.
Work Posts and Beds are still interactable, just Defence Posts.

**Comment by kuchuk-borom-debbarma** [comment]
latest update (3.1.3) uploaded 
Fixed this issue :) cheers
